<?php
declare(strict_types=1);

// Stripe SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

StripeUtility::setRegistrar(function (StripeUtility $u): void {
    $u->clean = [StripeClean::class, 'call'];
    $u->done = [StripeDone::class, 'call'];
    $u->make_error = [StripeMakeError::class, 'call'];
    $u->feature_add = [StripeFeatureAdd::class, 'call'];
    $u->feature_hook = [StripeFeatureHook::class, 'call'];
    $u->feature_init = [StripeFeatureInit::class, 'call'];
    $u->fetcher = [StripeFetcher::class, 'call'];
    $u->make_fetch_def = [StripeMakeFetchDef::class, 'call'];
    $u->make_context = [StripeMakeContext::class, 'call'];
    $u->make_options = [StripeMakeOptions::class, 'call'];
    $u->make_request = [StripeMakeRequest::class, 'call'];
    $u->make_response = [StripeMakeResponse::class, 'call'];
    $u->make_result = [StripeMakeResult::class, 'call'];
    $u->make_point = [StripeMakePoint::class, 'call'];
    $u->make_spec = [StripeMakeSpec::class, 'call'];
    $u->make_url = [StripeMakeUrl::class, 'call'];
    $u->param = [StripeParam::class, 'call'];
    $u->prepare_auth = [StripePrepareAuth::class, 'call'];
    $u->prepare_body = [StripePrepareBody::class, 'call'];
    $u->prepare_headers = [StripePrepareHeaders::class, 'call'];
    $u->prepare_method = [StripePrepareMethod::class, 'call'];
    $u->prepare_params = [StripePrepareParams::class, 'call'];
    $u->prepare_path = [StripePreparePath::class, 'call'];
    $u->prepare_query = [StripePrepareQuery::class, 'call'];
    $u->graphql_body = [StripeGraphql::class, 'body'];
    $u->graphql_errors = [StripeGraphql::class, 'errors'];
    $u->result_basic = [StripeResultBasic::class, 'call'];
    $u->result_body = [StripeResultBody::class, 'call'];
    $u->result_headers = [StripeResultHeaders::class, 'call'];
    $u->transform_request = [StripeTransformRequest::class, 'call'];
    $u->transform_response = [StripeTransformResponse::class, 'call'];
});
